### ISSUE TITLE
Comparison with prior art

### ISSUE THREAD

**Issue by dandv** [mrbar42/node-graceful#6]
Thank you for publishing this module!

Given that @jprichardson's [node-death](https://github.com/jprichardson/node-death) and @jtlapp's [node-cleanup](https://github.com/jtlapp/node-cleanup/issues/9) precede it, I'm curious to know how this module differs from [prior art](http://slides.com/dandv/prior-art#/5/6). Thanks!

**Comment by mrbar42** [comment]
well, this module exists before node-cleanup :smile: 

I guess for some reason i didn't find node-death when i was needing this functionality.
I've been using it for a while and eventually decided to publish it.

on a technical note the differences seem to be:
- Graceful supports forcing an exitCode 
- node-death handle `SIGHUP` differently
- Graceful allows a exit-on-double-signal functionality
- node-cleanup allows customizing the `Ctrl-C` message
- some more minor differences
