### ISSUE TITLE
Consider changing license to MIT or Apache 2.0

### ISSUE THREAD

**Issue by dandv** [mrbar42/node-graceful#7]
Certain corporate environments disallow using WTFPL-licensed software for legal reasons.

**Comment by mrbar42** [comment]
Could you explain how is that possible?
WTFPL is very close to no-license, what would be the reason for disliking WTFPL?

**Comment by dandv** [comment]
I'm not a lawyer, but I work at Google, and due to legal reasons above my paygrade, we cannot use WTFPL software, and for Public domain, a legal review is required.

For WTFPL, the reasons are:

> This license has a large number of issues (lack of warranty disclaimer, very vague rights grant), and was also rejected as an open source license by OSI. We also do not allow *contribution* to projects under WTFPL.

**Comment by mrbar42** [comment]
looked into this to your request.
Even though I perceive WTFPL as everything-is-allowed, it looks like some people find negativity in it to the point of [calling it "offensive"](https://github.com/dimitri/el-get/issues/474).
Also didn't really considered the legal implications it might have for organisations but i'll take your word that it could be problematic.

I see no reason why MIT wouldn't satisfy my agenda just as good - changed in https://github.com/mrbar42/node-graceful/pull/9

Thanks for this.
