### ISSUE TITLE
Catching JavaScript errors

### ISSUE THREAD

**Issue by dandv** [mrbar42/node-graceful#8]
How can Graceful listen for, e.g. TypeError, or ReferenceError? node-cleanup does that by default.

**Comment by mrbar42** [comment]
Thanks for this!

do you mean adding event listener for `uncaughtException`s?
it's definitely possible, i just wonder if most of the people would like `Graceful` to kill their process on error.
newer node behaves like that by default

**Comment by mrbar42** [comment]
Added suggested functionality in [v3](https://github.com/mrbar42/node-graceful/releases/tag/v3.0.0)
